<?php 
use Zend\Form\View\Helper\FormElement;
use Zend\Session\Container;
$form->setAttribute('action', $this->url('friend', array('action' => 'update')));
if($this->error):
?>
<title>SOCIAL MEDIA</title>
<p class="error">
Erro, desculpe.
</p>
<?php endif; 


$form = $this->form;
$form->prepare();
echo $this->form()->openTag($form);
?>
<form class="form-horizontal">
	<div class="container">
	  <h1 class="text-center login-title">Pessoas Encontradas</h1>
		<?php 
	        $flash = $this->flashMessenger();
	        $flash->setMessageOpenFormat('<div%s>
				<button type="button" class="close" data-dismiss="alert" aria-hidden="true">
			    	&times;
			    </button>
			<ul><li>')
	        ->setMessageSeparatorString('</li><li>')
			->setMessageCloseString('</li></ul></div>');
			echo $flash->render('error',   array('alert', 'alert-dismissible', 'alert-danger'));        							    
			echo $flash->render('info',    array('alert', 'alert-dismissible', 'alert-info'));
			echo $flash->render('default', array('alert', 'alert-dismissible', 'alert-warning'));
			echo $flash->render('success', array('alert', 'alert-dismissible', 'alert-success'));
		?>
		 <div class="jumbotron" style="min-height:400px;height:auto;">
		<ul class="list-group">
		<?php
		$sessao = new Container('Auth');
		$idUsuario = $sessao->idUsuario;
		
		foreach ($pessoas as $pessoa){
			echo '<li class="list-group-item user-item text-left">';
			$validator = new \Zend\Validator\File\Exists();
			$validator->addDirectory('public/img/');
			$img = "fotoperfil_".$pessoa['codUsuario'].".jpg";
				
			if($validator->isValid($img)){
				echo '<img class="img-circle img-user" src="img/'.$img.'">';
			} else {
				echo '<img class="img-circle img-user" src="img/avatar.png">';
			}
			
			echo '<h3>';
			echo '<b>Nome: </b>' . $pessoa['nome'] . '<br>';
			echo '<b>Status: </b>' . $pessoa['descricaoStatus'] . '<br>';
			echo '<b>Email: </b>' . $pessoa['email'] . '<br>';
			echo '</h3>';
				
			if(!$pessoa['situacao']) {
				echo '<a href="/friend/add/'.$pessoa['codUsuario'].'"><button type="button" class="btn btn-success pull-right">Adicionar</button></a>';
			} else if ($pessoa['situacao'] == 'P' && $pessoa['idSolicitado'] == $idUsuario) {
				echo '<a href="/friend/addpend/'.$pessoa['codAmigo'].'"><button type="button" class="btn btn-info pull-right">Aceitar</button></a>';
				echo '<a href="/friend/rec/'.$pessoa['codAmigo'].'"><button type="button" class="btn btn-warning pull-right">Recusar</button></a>';
			} else if ($pessoa['situacao'] == 'P') {
				echo '<button type="button" class="btn btn-warning pull-right">Pendente</button>';
			} else if ($pessoa['situacao'] == 'A') {
				echo '<button type="button" class="btn btn-primary pull-right">Amigo</button>';
				echo '<a href="/friend/remove/'.$pessoa['codAmigo'].'"><button type="button" class="btn btn-danger pull-right">Excluir</button></a>';
			} else if ($pessoa['situacao'] == 'R' && $pessoa['idSolicitado'] != $idUsuario){
				echo '<a href="/friend/addagain/'.$pessoa['codAmigo'].'"><button type="button" class="btn btn-danger pull-right">O Pedido de amizade foi recusado, Tentar Adicionar Novamente</button></a>';
			} else if ($pessoa['situacao'] == 'R') {
				echo '<button type="button" class="btn btn-danger pull-right">Recusado</button>';
			}
			
			
			echo '</li>';
			
		}
		?>
		</ul>
		</div>
	      <a href = "javascript:history.back()"><button type="button" class="btn btn-primary">Voltar</button></a>
	      <?php //echo $this->formElement($form->get('submit'));?>
	</div>
</form>
<?php echo $this->form()->closeTag($form); ?>