<?php 
use Zend\Form\View\Helper\FormElement;
$form->setAttribute('action', $this->url('login', array('action' => 'login')));
if($this->error):
?>
<title>SOCIAL MEDIA</title>
<p class="error">
Erro, desculpe.
</p>
<?php endif; 


$form = $this->form;
$form->prepare();
echo $this->form()->openTag($form);
?>
</style>
<div class="container">
    <div class="row">
        <div class="col-sm-6 col-md-4 col-md-offset-4">
        <h1 class="text-center login-title">Login</h1>
	        <div class="account-wall">
	        	<form class="form-signin">
	        		<?php 
						echo $this->flashMessenger()->renderCurrent('error', array('alert', 'alert-danger'));
						echo $this->flashMessenger()->renderCurrent('success', array('alert', 'alert-success'));
						echo $this->flashMessenger()->renderCurrent('default', array('alert', 'alert-info'));
					?>
					<?php  echo $this->formlabel($form->get('e-mail')); ?>
					<?php  echo $this->formelement($form->get('e-mail')); ?>
					<?php  echo $this->formlabel($form->get('senha')); ?>
					<?php  echo $this->formelement($form->get('senha')); ?>
					<br>
					<?php echo $this->formElement($form->get('submit'));?>
				</form>
				<a href="register/" class="pull-right need-help">Criar uma conta.</a>
			</div>
		</div>
	</div>
</div>			
<?php echo $this->form()->closeTag($form); ?>