<?php 
use Zend\Form\View\Helper\FormElement;
$form->setAttribute('action', $this->url('login', array('action' => 'login')));
if($this->error):
?>
<title>SOCIAL MEDIA</title>
<p class="error">
Erro, desculpe.
</p>
<?php endif; 


$form = $this->form;
$form->prepare();
echo $this->form()->openTag($form);
?>
</style>
<div class="container">
    <div class="row">
        <div class="col-sm-6 col-md-4 col-md-offset-4">
        <h1 class="text-center login-title">Login</h1>
	        <div class="account-wall">
	        	<form class="form-signin">
	        		<?php 
	        		$flash = $this->flashMessenger();
	        		$flash->setMessageOpenFormat('<div%s>
						<button type="button" class="close" data-dismiss="alert" aria-hidden="true">
					    	&times;
					    </button>
					<ul><li>')
	        	    ->setMessageSeparatorString('</li><li>')
				    ->setMessageCloseString('</li></ul></div>');
				    echo $flash->render('error',   array('alert', 'alert-dismissible', 'alert-danger'));        							    
				    echo $flash->render('info',    array('alert', 'alert-dismissible', 'alert-info'));
				    echo $flash->render('default', array('alert', 'alert-dismissible', 'alert-warning'));
				    echo $flash->render('success', array('alert', 'alert-dismissible', 'alert-success'));
	        							     
	        		?>
					<?php  echo $this->formlabel($form->get('e-mail')); ?>
					<?php  echo $this->formelement($form->get('e-mail')); ?>
					<?php  echo $this->formlabel($form->get('senha')); ?>
					<?php  echo $this->formelement($form->get('senha')); ?>
					<br>
					<?php echo $this->formElement($form->get('submit'));?>
				</form>
				<a href="register/" class="pull-right need-help">Criar uma conta.</a>
			</div>
		</div>
	</div>
</div>			
<?php echo $this->form()->closeTag($form); ?>