<?php 
use Zend\Form\View\Helper\FormElement;
$form->setAttribute('action', $this->url('login', array('action' => 'create')));
if($this->error):
?>
<p class="error">
Erro, desculpe.
</p>
<?php endif; 

$form = $this->form;
$form->prepare();
echo $this->form()->openTag($form);
?>

<div class="container">
    <div class="row">
        <div class="col-sm-6 col-md-4 col-md-offset-4">
        <h1 class="text-center login-title">Nova Conta</h1>
	        <div class="account-wall">
	        	<form class="form-signin" id="registerForm">
	        		<?php 
						echo $this->flashMessenger()->renderCurrent('error', array('alert', 'alert-danger'));
						echo $this->flashMessenger()->renderCurrent('success', array('alert', 'alert-success'));
						echo $this->flashMessenger()->renderCurrent('default', array('alert', 'alert-info'));
						echo $this->formlabel($form->get('nome'));
						echo $this->formelement($form->get('nome')); 
					 	echo $this->formlabel($form->get('email')); 
						echo $this->formelement($form->get('email')); 
					  	echo $this->formlabel($form->get('senha')); 
					  	echo $this->formelement($form->get('senha')); 
					  	echo $this->formlabel($form->get('confirmaSenha')); 
					  	echo $this->formelement($form->get('confirmaSenha'));
					  ?>
					<br>
					<?php echo $this->formElement($form->get('submit'));?>
				</form>
			</div>
		</div>
	</div>
</div>
<?php echo $this->form()->closeTag($form); ?>
