<?php 
use Zend\Session\Container;

$sessao = new Container('Auth');
$nome = $sessao -> nome;

echo $this->doctype(); 
function echoActiveClassIfRequestMatches($requestUri)
{
	$current_file_name = basename($_SERVER['REQUEST_URI'], ".php");

	if ($current_file_name == $requestUri)
		echo 'class="active"';
}
?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Social Media'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') 
                        ->prependStylesheet($this->basePath() . '/css/login.css')
        ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body class="backgroundtime">
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img src="<?php echo $this->basePath('img/zf2-logo.png') ?>" alt="Zend Framework 2"/>&nbsp;<?php echo $this->translate('Skeleton Application') ?></a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li <?=echoActiveClassIfRequestMatches("timeline")?> ><a href="<?php echo $this->url('timeline') ?>"><?php echo $this->translate('Linha do Tempo') ?></a></li>
                        <li <?=echoActiveClassIfRequestMatches("register")?>><a href="<?php echo $this->url('register') ?>"><?php echo $this->translate('Amigos') ?></a></li>
			            <li class="dropdown">
			            	<a href="#" class="dropdown-toggle" data-toggle="dropdown" ><?php echo $nome; ?></a>
			              	<ul class="dropdown-menu">
           				  		<li <?=echoActiveClassIfRequestMatches("user")?>><a href="<?php echo $this->url('user') ?>"><?php echo $this->translate('Conta') ?></a></li>
		              		</ul>
			            </li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
						<li <?=echoActiveClassIfRequestMatches("logout")?>><a title="Logout" class="glyphicon glyphicon-off" href="<?php echo $this->url('logout') ?>"></a></li>
                    </ul>
					<div class="col-sm-3 col-md-4">
						<form class="navbar-form" role="search" action="/friend" method="post">
							<div class="input-group">
								<input type="text" class="form-control" placeholder="Procure pessoas pelo nome"
									name="searchPer" id="searchPer">
								<div class="input-group-btn">
									<button class="btn btn-default" type="submit">
										<i class="glyphicon glyphicon-search"></i>
									</button>
								</div>
							</div>
						</form>
					</div>
			</div><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; 2005 - <?php echo date('Y') ?> by Zend Technologies Ltd. <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
        <script>
		$(document).ready(function(){
		    $('[data-toggle="tooltip"]').tooltip();
		});
		</script>
    </body>
</html>
